import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cookie App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`inter.className overflow-y-hidden`}>
        <div className="navbar bg-gray-900 p-1 text-white flex justify-center">
          <Navbar />
        </div>
        <main className="m-4">{children}</main>
      </body>
    </html>
  );
}
